import { useCallback, useEffect, useRef, useState } from 'react';
import { faker } from '@faker-js/faker';
import { useMaintenanceContext } from '@/context/MaintenanceRecordsContext';
import { cls } from '@/styles/classes';
import type { MaintenanceRecord, MaintenanceServiceType } from '@/types';
import { AnalyticsCharts } from './analytics/AnalyticsCharts';

const AUTO_ADD_INTERVAL_MS = 5000;

const AUTO_SERVICE_TYPES: ReadonlyArray<MaintenanceServiceType> = [
  'OIL_CHANGE',
  'BRAKE_SERVICE',
  'TIRE_SERVICE',
  'ENGINE_SERVICE',
  'INSPECTION',
  'OTHER',
];

const SERVICE_BASE_COST: Record<MaintenanceServiceType, number> = {
  OIL_CHANGE: 72,
  BRAKE_SERVICE: 180,
  TIRE_SERVICE: 95,
  ENGINE_SERVICE: 420,
  INSPECTION: 125,
  OTHER: 80,
};

type AutoGeneratedCar = {
  id: string;
  userId: string;
  make: string;
  model: string;
  year: number;
  mileageKm: number;
};

function toIsoDateOnly(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function createFakerCar(sequence: number): AutoGeneratedCar {
  return {
    id: `auto-car-${sequence}-${faker.string.alphanumeric(6).toLowerCase()}`,
    userId: `auto-user-${faker.string.alphanumeric(8).toLowerCase()}`,
    make: faker.vehicle.manufacturer(),
    model: faker.vehicle.model(),
    year: faker.number.int({ min: 2008, max: 2026 }),
    mileageKm: faker.number.int({ min: 18000, max: 220000 }),
  };
}

function createAutoRecord(sequence: number): MaintenanceRecord {
  const car = createFakerCar(sequence);
  const serviceType = faker.helpers.arrayElement(AUTO_SERVICE_TYPES);
  const serviceDate = toIsoDateOnly(faker.date.recent({ days: 45 }));
  const odometerKm = car.mileageKm;
  const costUsd = Number((SERVICE_BASE_COST[serviceType] + faker.number.int({ min: 5, max: 90 })).toFixed(2));
  const providerName = faker.company.name();
  const providerLocation = faker.location.city();

  return {
    id: `auto-${faker.string.uuid()}`,
    userId: car.userId,
    carId: car.id,
    serviceType,
    serviceDate,
    odometerKm,
    nextServiceKm: odometerKm + faker.number.int({ min: 4000, max: 9000 }),
    costUsd,
    providerName,
    providerLocation,
    notes: `Generated for ${car.year} ${car.make} ${car.model} every ${AUTO_ADD_INTERVAL_MS / 1000} seconds for analytics simulation.`,
    createdAt: serviceDate,
    updatedAt: serviceDate,
  };
}

export function DashboardOverviewAnalyticsPanel() {
  const { records: contextRecords } = useMaintenanceContext();
  const [records, setRecords] = useState<ReadonlyArray<MaintenanceRecord>>(contextRecords);
  const [generatedCount, setGeneratedCount] = useState(0);
  const [isRunning, setIsRunning] = useState(false);
  const sequenceRef = useRef(0);

  useEffect(() => {
    setRecords(contextRecords);
    setGeneratedCount(0);
    sequenceRef.current = 0;
  }, [contextRecords]);

  const appendRecord = useCallback(() => {
    sequenceRef.current += 1;
    const autoRecord = createAutoRecord(sequenceRef.current);

    setRecords((previous) => [...previous, autoRecord]);
    setGeneratedCount((previous) => previous + 1);
  }, []);

  useEffect(() => {
    if (!isRunning) {
      return undefined;
    }

    const intervalId = window.setInterval(() => {
      appendRecord();
    }, AUTO_ADD_INTERVAL_MS);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [appendRecord, isRunning]);

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Dashboard Overview</h1>
        <p className="mt-2 text-sm text-gray-600">
          Compare maintenance records and analytics side by side.
        </p>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-3 shadow-sm sm:flex sm:items-center sm:justify-between sm:gap-4">
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={() => setIsRunning(true)}
            disabled={isRunning}
            className={isRunning ? cls.btnDisabled : cls.btnPrimary}
          >
            Start Auto Add (5s)
          </button>

          <button
            type="button"
            onClick={() => setIsRunning(false)}
            disabled={!isRunning}
            className={isRunning ? cls.btnDanger : cls.btnDisabled}
          >
            Stop
          </button>
        </div>

        <p className="mt-3 text-sm text-gray-600 sm:mt-0">
          Status: <span className={isRunning ? 'font-semibold text-emerald-600' : 'font-semibold text-gray-700'}>{isRunning ? 'Running' : 'Stopped'}</span>
          {' '}• Added records: <span className="font-semibold text-gray-900">{generatedCount}</span>
        </p>
      </div>

      <AnalyticsCharts recordsOverride={records} />
    </div>
  );
}